# -*- coding: utf-8 -*-
"""final_fr&spTraslator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uypxtpUUq--gjiMlx6X6qtt-uk6nZe4Z
"""

# 👇 Ejecuta esta celda en Google Colab
!pip install -q transformers torch sentencepiece gradio

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import gradio as gr
import torch

# Cargar el modelo NLLB-200 (ligero para CPU o GPU)
model_name = "facebook/nllb-200-distilled-600M"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Verificar y mover el modelo a la GPU si está disponible
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)  # Mover el modelo a la GPU

# Códigos de idioma
idiomas = {
    "Español → Francés": ("spa_Latn", "fra_Latn"),
    "Francés → Español": ("fra_Latn", "spa_Latn")
}

def traducir(texto, direccion):
    print(f"Texto recibido: {texto}")
    src_lang, tgt_lang = idiomas[direccion]

    # Establecer los idiomas en el tokenizer
    tokenizer.src_lang = src_lang
    tokenizer.tgt_lang = tgt_lang

    # Tokenizar el texto con el idioma de origen
    inputs = tokenizer(texto, return_tensors="pt", padding=True).to(device)

    # Generar la traducción
    with torch.no_grad():
        generated_tokens = model.generate(
            **inputs,
            max_length=10000,
            num_beams=4,
            forced_bos_token_id=tokenizer.convert_tokens_to_ids(tgt_lang)
        )

    # Decodificar los tokens generados
    traduccion = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)[0]
    return traduccion

# Prueba con una frase de ejemplo
texto_prueba = "Hola, ¿cómo estás?"
direccion_prueba = "Español → Francés"

# Llamar a la función de traducción
traduccion_resultado = traducir(texto_prueba, direccion_prueba)
print(f"Traducción final: {traduccion_resultado}")

# Crear la interfaz de Gradio
interfaz = gr.Interface(
    fn=traducir,
    inputs=[
        gr.Textbox(label="Frase", placeholder="Escribe una frase..."),
        gr.Radio(choices=list(idiomas.keys()), value="Español → Francés", label="Dirección de Traducción")
    ],
    outputs=gr.Textbox(label="Traducción"),
    title="Traductor Español ↔ Francés con NLLB",
    description="Traducción neuronal usando Meta AI (NLLB-200)",
    article="Creado por: **Mayra Sánchez** y **Víctor Gaytán**",
    allow_flagging="never"
)

# Lanzar la interfaz en Colab
interfaz.launch(share = True, inline = True)

